site_name: Endades Newsletter
# site_favicon: img/favicon.ico

theme:
  name: readthedocs
  highlightjs: true
  # logo: img/endades.png
  # favicon: images/Time2_16x16.png
  

### Change font style ###
extra_css:
  - stylesheets/custom.css

#extra_javascript:
#  - assets/javascripts/search-highlight.js

### Hide logos and copy rights ###
extra:
  hide:
    github: true
    edit_page: true

copyright: " "

extra_javascript:
  - js/auth-modal.js

### Menu navegation ###
nav:
  - Home: index.md
  - Development:
    - ENBLAU: Development/ENBLAU_Dev.md
    - enCONTROL: Development/enCONTROL_Dev.md
    - enSITE: Development/enSITE_Dev.md
    - enMATERIALS: Development/enMATERIALS_Dev.md
    - enCAD: Development/enCAD_Dev.md
    - enCLAD: Development/enCLAD_Dev.md
    - enUPDATE: Development/enUPDATE_Dev.md
    - enCONNECT: Development/enCONNECT_Dev.md
    - ENBLAU WEB: Development/ENBLAU_WEB_Dev.md

